---
title: "Projects"
---

-   **The Development of an Accessible, Diverse and Inclusive Digital Visual Language** – Icons, symbols, and signs represent a visual language that facilitates communication because it conveys large amounts of information in single units intended to be understood by everyone irrespective of culture or language. The development of a visual language of icons and symbols that is accessible, inclusive, diverse and neutral is of paramount importance now that the number of digital interfaces that use such language keep expanding at a global level. The proposed project is the first to gather evidence from a diverse population that will be, by default inclusive, and create web application to make those evidence-based guidelines easily accessible to all. This knowledge will be disseminated to a wider audience to promote better use of icon design that is inclusive to a wider audience; one that includes different cultures and languages. From research outputs of the first stage of the project, with the help of the RA we will design and build a machine learning model to learn how icons are rated across groups based on their 7 key properties. This machine learning model will provide the classification and usability scores that will form the basis of an online searchable database for all the key icon characteristics, thereby removing the obstacles for developers to use good icons based on research-backed principles.

    -   Project Name: The Development of an Accessible, Diverse and Inclusive Digital Visual Language
    -   Awarded: August 2022
    -   Awarding Body: Morgan Advanced Studies Institute (MASI)

-   **PREdicting Solar Activity using machine learning on heteroGEneous data (PRESAGE)** – Our project concerns itself with the activity of the Sun, those events (e.g. flares, coronal mass ejections (CME)) are dynamical phenomena that may have strong impacts on the solar-terrestrial environment. Events of solar activity seem to be strongly associated with the evolution of solar structures (e.g. active regions, filaments), which are objects of the solar atmosphere that differ from the “quiet Sun” and which appear, evolve, and disappear over a period of days to months. The exact mechanisms of solar activity, and the links between solar structures and activity events, are still ill-understood.

    -   Project Name: PREdicting Solar Activity using machine learning on heteroGEneous data (PRESAGE)

-   **Developing Resilience against Online Grooming (DRaOG)** – The grant application was based on the research outputs of \`Integrating linguistic knowledge into DNNs: Application to online grooming detection'. This work and its outputs were included in a grant application to further collaborate with police forces and social workers in the UK. This grant is a collaborative effort between the Department of Computer Science, and College of Law, Swansea, and Université de Toulon, France. More information about the grant and the funding body can be found on the End Violence Against Children website at <https://www.end-violence.org/grants/swansea-university> and at the Project's website: <https://www.swansea.ac.uk/project-dragon-s/>

    -   Project Name: DRAGON-S
    -   Awarded: January 2021
    -   Awarding Body: End Violence Against Children (EVAC)
